In [15]:
import numpy as np
import statsmodels.api as sm
import pandas as pd

In [16]:
police_allegations = pd.read_csv('./allegations_202007271729.csv', index_col=0)
police_allegations.head()

first_name last_name command_now  shield_no  complaint_id  \
unique_mos_id                                                             
10004           Jonathan      Ruiz     078 PCT       8409         42835   
10007               John     Sears     078 PCT       5952         24601   
10007               John     Sears     078 PCT       5952         24601   
10007               John     Sears     078 PCT       5952         26146   
10009              Noemi    Sierra     078 PCT      24058         40253   

               month_received  year_received  month_closed  year_closed  \
unique_mos_id                                                             
10004                       7           2019             5         2020   
10007                      11           2011             8         2012   
10007                      11           2011             8         2012   
10007                       7           2012             9         2013   
10009                       8           2018             2         2019   

              command_at_incident  ... mos_age_incident complainant_ethnicity  \
unique_mos_id                      ...                                          
10004                     078 PCT  ...               32                 Black   
10007                        PBBS  ...               24                 Black   
10007                        PBBS  ...               24                 Black   
10007                        PBBS  ...               25                 Black   
10009                     078 PCT  ...               39                   NaN   

              complainant_gender complainant_age_incident           fado_type  \
unique_mos_id                                                                   
10004                     Female                     38.0  Abuse of Authority   
10007                       Male                     26.0         Discourtesy   
10007                       Male                     26.0  Offensive Language   
10007                       Male                     45.0  Abuse of Authority   
10009                        NaN                     16.0               Force   

                                 allegation  precinct  \
unique_mos_id                                           
10004          Failure to provide RTKA card      78.0   
10007                                Action      67.0   
10007                                  Race      67.0   
10007                              Question      67.0   
10009                        Physical force      67.0   

                                             contact_reason  \
unique_mos_id                                                 
10004                               Report-domestic dispute   
10007                                      Moving violation   
10007                                      Moving violation   
10007          PD suspected C/V of violation/crime - street   
10009                                        Report-dispute   

                            outcome_description  \
unique_mos_id                                     
10004          No arrest made or summons issued   
10007           Moving violation summons issued   
10007           Moving violation summons issued   
10007          No arrest made or summons issued   
10009            Arrest - other violation/crime   

                                      board_disposition  
unique_mos_id                                            
10004          Substantiated (Command Lvl Instructions)  
10007                           Substantiated (Charges)  
10007                           Substantiated (Charges)  
10007                           Substantiated (Charges)  
10009              Substantiated (Command Discipline A)  

[5 rows x 26 columns]

In [17]:
df = police_allegations[police_allegations.complainant_gender != 'Transgender']

df.head()
tempdf1 = police_allegations[police_allegations.complainant_ethnicity == 'White']
whitedf_male = tempdf1[tempdf1.complainant_gender == 'Male']


tempdf = police_allegations[police_allegations.complainant_ethnicity == 'Black']
blackdf_male = tempdf[tempdf.complainant_gender == 'Male']

whitedf_male.head()

first_name last_name command_now  shield_no  complaint_id  \
unique_mos_id                                                             
10012              Paula     Smith     078 PCT       4021         37256   
10014            Malachy  Sullivan     078 PCT       4143         33969   
10042               John   Musante     079 DET         15         10247   
10042               John   Musante     079 DET         15         33550   
10042               John   Musante     079 DET         15         33550   

               month_received  year_received  month_closed  year_closed  \
unique_mos_id                                                             
10012                       5           2017            10         2017   
10014                      11           2015             2         2016   
10042                      11           2005             5         2006   
10042                       9           2015             2         2016   
10042                       9           2015             2         2016   

              command_at_incident  ... mos_age_incident complainant_ethnicity  \
unique_mos_id                      ...                                          
10012                     078 PCT  ...               50                 White   
10014                     078 PCT  ...               43                 White   
10042                     025 PCT  ...               24                 White   
10042                     083 PCT  ...               34                 White   
10042                     083 PCT  ...               34                 White   

              complainant_gender complainant_age_incident           fado_type  \
unique_mos_id                                                                   
10012                       Male                     31.0  Abuse of Authority   
10014                       Male                     34.0  Offensive Language   
10042                       Male                     29.0  Abuse of Authority   
10042                       Male                     27.0  Abuse of Authority   
10042                       Male                     27.0  Abuse of Authority   

                                          allegation  precinct  \
unique_mos_id                                                    
10012          Refusal to process civilian complaint      78.0   
10014                             Sexual orientation      78.0   
10042                             Retaliatory arrest      25.0   
10042                                           Stop      83.0   
10042                                          Frisk      83.0   

                                             contact_reason  \
unique_mos_id                                                 
10012                                    C/V telephoned PCT   
10014          PD suspected C/V of violation/crime - street   
10042                                                 Other   
10042          PD suspected C/V of violation/crime - street   
10042          PD suspected C/V of violation/crime - street   

                            outcome_description  \
unique_mos_id                                     
10012          No arrest made or summons issued   
10014           Summons - other violation/crime   
10042            Arrest - other violation/crime   
10042          No arrest made or summons issued   
10042          No arrest made or summons issued   

                                      board_disposition  
unique_mos_id                                            
10012          Substantiated (Command Lvl Instructions)  
10014               Substantiated (Formalized Training)  
10042                                        Exonerated  
10042                                        Exonerated  
10042                                        Exonerated  

[5 rows x 26 columns]

In [18]:
df.groupby('complainant_ethnicity')['complainant_age_incident'].mean()

complainant_ethnicity
American Indian    31.968750
Asian              34.326376
Black              32.293317
Hispanic           31.828517
Other Race         32.122963
Refused            35.345238
Unknown            26.313772
White              36.747914
Name: complainant_age_incident, dtype: float64

# Dummy Coding

In [19]:
#dummy coding
from patsy.contrasts import Treatment
levels = [1,2,3,4]
contrast = Treatment(reference=0).code_without_intercept(levels)
print(contrast.matrix)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
df.complainant_ethnicity.head(10)

unique_mos_id
10004    Black
10007    Black
10007    Black
10007    Black
10009      NaN
10012    White
10014    White
10017    Asian
10017    Asian
10017    Asian
Name: complainant_ethnicity, dtype: object

In [21]:
pd.get_dummies(df.complainant_ethnicity.values, drop_first=False)
#pd.get_dummies(hsb2.race.values, drop_first=False)

American Indian  Asian  Black  Hispanic  Other Race  Refused  Unknown  \
0                    0      0      1         0           0        0        0   
1                    0      0      1         0           0        0        0   
2                    0      0      1         0           0        0        0   
3                    0      0      1         0           0        0        0   
4                    0      0      0         0           0        0        0   
...                ...    ...    ...       ...         ...      ...      ...   
33353                0      1      0         0           0        0        0   
33354                0      1      0         0           0        0        0   
33355                0      1      0         0           0        0        0   
33356                0      1      0         0           0        0        0   
33357                0      1      0         0           0        0        0   

       White  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
33353      0  
33354      0  
33355      0  
33356      0  
33357      0  

[33358 rows x 8 columns]

In [24]:
from statsmodels.formula.api import ols
#mod = ols("write ~ C(race, Treatment)", data=df)
mod = ols("complainant_age_incident ~ C(complainant_ethnicity, Treatment)", data=df)
res = mod.fit()
print(res.summary())

                               OLS Regression Results                               
Dep. Variable:     complainant_age_incident   R-squared:                       0.004
Model:                                  OLS   Adj. R-squared:                  0.004
Method:                       Least Squares   F-statistic:                     15.75
Date:                      Tue, 16 Mar 2021   Prob (F-statistic):           9.01e-21
Time:                              02:36:57   Log-Likelihood:            -1.3507e+05
No. Observations:                     28336   AIC:                         2.702e+05
Df Residuals:                         28328   BIC:                         2.702e+05
Df Model:                                 7                                         
Covariance Type:                  nonrobust                                         
                                                        coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------

# Simple Coding

In [25]:
#simple coding
from patsy.contrasts import ContrastMatrix

def _name_levels(prefix, levels):
    return ["[%s%s]" % (prefix, level) for level in levels]

class Simple(object):
    def _simple_contrast(self, levels):
        nlevels = len(levels)
        contr = -1./nlevels * np.ones((nlevels, nlevels-1))
        contr[1:][np.diag_indices(nlevels-1)] = (nlevels-1.)/nlevels
        return contr

    def code_with_intercept(self, levels):
        contrast = np.column_stack((np.ones(len(levels)),
                                    self._simple_contrast(levels)))
        return ContrastMatrix(contrast, _name_levels("Simp.", levels))

    def code_without_intercept(self, levels):
        contrast = self._simple_contrast(levels)
        return ContrastMatrix(contrast, _name_levels("Simp.", levels[:-1]))

In [26]:
df.groupby('complainant_gender')['complainant_age_incident'].mean().mean()

35.37454411757087

In [27]:
contrast = Simple().code_without_intercept(levels)
print(contrast.matrix)

[[-0.25 -0.25 -0.25]
 [ 0.75 -0.25 -0.25]
 [-0.25  0.75 -0.25]
 [-0.25 -0.25  0.75]]


In [29]:
mod = ols("complainant_age_incident ~ C(complainant_ethnicity, Simple)", data=df)
res = mod.fit()
print(res.summary())

                               OLS Regression Results                               
Dep. Variable:     complainant_age_incident   R-squared:                       0.004
Model:                                  OLS   Adj. R-squared:                  0.004
Method:                       Least Squares   F-statistic:                     15.75
Date:                      Tue, 16 Mar 2021   Prob (F-statistic):           9.01e-21
Time:                              02:38:27   Log-Likelihood:            -1.3507e+05
No. Observations:                     28336   AIC:                         2.702e+05
Df Residuals:                         28328   BIC:                         2.702e+05
Df Model:                                 7                                         
Covariance Type:                  nonrobust                                         
                                                             coef    std err          t      P>|t|      [0.025      0.975]
---------------------------

# Sum/Deviation Coding

In [30]:
#sum/deviation coding
from patsy.contrasts import Sum
contrast = Sum().code_without_intercept(levels)
print(contrast.matrix)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [-1. -1. -1.]]


In [31]:
mod = ols("complainant_age_incident ~ C(complainant_ethnicity, Sum)", data=df)
res = mod.fit()
print(res.summary())

                               OLS Regression Results                               
Dep. Variable:     complainant_age_incident   R-squared:                       0.004
Model:                                  OLS   Adj. R-squared:                  0.004
Method:                       Least Squares   F-statistic:                     15.75
Date:                      Tue, 16 Mar 2021   Prob (F-statistic):           9.01e-21
Time:                              02:38:54   Log-Likelihood:            -1.3507e+05
No. Observations:                     28336   AIC:                         2.702e+05
Df Residuals:                         28328   BIC:                         2.702e+05
Df Model:                                 7                                         
Covariance Type:                  nonrobust                                         
                                                       coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------

In [32]:
df.groupby('complainant_ethnicity')['complainant_age_incident'].mean().mean()

32.618355959172504

# Backward Difference Coding

In [33]:
#backward difference coding
from patsy.contrasts import Diff
contrast = Diff().code_without_intercept(levels)
print(contrast.matrix)

[[-0.75 -0.5  -0.25]
 [ 0.25 -0.5  -0.25]
 [ 0.25  0.5  -0.25]
 [ 0.25  0.5   0.75]]


In [34]:
mod = ols("complainant_age_incident ~ C(complainant_ethnicity, Diff)", data=df)
res = mod.fit()
print(res.summary())

                               OLS Regression Results                               
Dep. Variable:     complainant_age_incident   R-squared:                       0.004
Model:                                  OLS   Adj. R-squared:                  0.004
Method:                       Least Squares   F-statistic:                     15.75
Date:                      Tue, 16 Mar 2021   Prob (F-statistic):           9.01e-21
Time:                              02:39:28   Log-Likelihood:            -1.3507e+05
No. Observations:                     28336   AIC:                         2.702e+05
Df Residuals:                         28328   BIC:                         2.702e+05
Df Model:                                 7                                         
Covariance Type:                  nonrobust                                         
                                                        coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------

# Helmert Polynomial Coding

In [35]:
#helmert coding
from patsy.contrasts import Helmert
contrast = Helmert().code_without_intercept(levels)
print(contrast.matrix)

[[-1. -1. -1.]
 [ 1. -1. -1.]
 [ 0.  2. -1.]
 [ 0.  0.  3.]]


In [36]:
mod = ols("complainant_age_incident ~ C(complainant_ethnicity, Helmert)", data=df)
res = mod.fit()
print(res.summary())

                               OLS Regression Results                               
Dep. Variable:     complainant_age_incident   R-squared:                       0.004
Model:                                  OLS   Adj. R-squared:                  0.004
Method:                       Least Squares   F-statistic:                     15.75
Date:                      Tue, 16 Mar 2021   Prob (F-statistic):           9.01e-21
Time:                              02:39:48   Log-Likelihood:            -1.3507e+05
No. Observations:                     28336   AIC:                         2.702e+05
Df Residuals:                         28328   BIC:                         2.702e+05
Df Model:                                 7                                         
Covariance Type:                  nonrobust                                         
                                                      coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------

# Orthogonal Polynomial Coding

In [40]:
#orthogonal polynomial coding
df['mos_age_incident_cat'] = np.asarray(pd.cut(df.mos_age_incident, bins=3))
df.groupby('mos_age_incident_cat').mean()['complainant_age_incident']

mos_age_incident_cat
(19.96, 33.333]     31.802441
(33.333, 46.667]    33.405294
(46.667, 60.0]      36.590769
Name: complainant_age_incident, dtype: float64

In [41]:
from patsy.contrasts import Poly
levels = df.mos_age_incident_cat.unique().tolist()
contrast = Poly().code_without_intercept(levels)
print(contrast.matrix)

[[-7.07106781e-01  4.08248290e-01]
 [-4.43378006e-17 -8.16496581e-01]
 [ 7.07106781e-01  4.08248290e-01]]


In [42]:
mod = ols("complainant_age_incident ~ C(mos_age_incident_cat, Poly)", data=df)
res = mod.fit()
print(res.summary())

                               OLS Regression Results                               
Dep. Variable:     complainant_age_incident   R-squared:                       0.001
Model:                                  OLS   Adj. R-squared:                  0.001
Method:                       Least Squares   F-statistic:                     17.27
Date:                      Tue, 16 Mar 2021   Prob (F-statistic):           3.20e-08
Time:                              02:47:07   Log-Likelihood:            -1.3602e+05
No. Observations:                     28546   AIC:                         2.721e+05
Df Residuals:                         28543   BIC:                         2.721e+05
Df Model:                                 2                                         
Covariance Type:                  nonrobust                                         
                                              coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------